plugins {
    id 'java'
}

group = 'org.lwjgl.glfw'

configurations.default.setCanBeResolved(true)

jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    archiveBaseName = "lwjgl-glfw-classes"
    from {
        configurations.default.collect {
            println(it.getName())
            it.isDirectory() ? it : zipTree(it)
        }
    }
    exclude 'net/java/openjdk/cacio/ctc/**'
    exclude 'org/lwjgl/input/Mouse.class'
    exclude 'org/lwjgl/input/Mouse$EmptyCursorGrabListener.class'
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
}
